version: '2'
services:
  builder:
    image: node:6.10.1
    volumes:
      - .:/builder/
    working_dir: /builder/
  worker:
    #restart: always
    image: node:6.10.1
    volumes:
      - ./worker/simpleWorker.js:/apps/simpleWorker.js
    working_dir: /apps
    command: node /apps/simpleWorker.js
    env_file: worker.env
  loopback-mongo-sandbox:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/apps/loopback-mongo-sandbox
    depends_on:
     - mongo
    env_file: .env
  mongo:
    image: mongo
    ports:
      - "3001:27017"
  worker-framework:
    build: https://github.com/ShoppinPal/node-worker.git
    env_file: .env
    depends_on:
     - mongo
